chore(ci): test MinEmacs in daemon mode

diff --git a/.github/workflows/ci-linux.yaml b/.github/workflows/ci-linux.yaml
--- a/.github/workflows/ci-linux.yaml
+++ b/.github/workflows/ci-linux.yaml
@@ -90,4 +90,27 @@ jobs:
             echo -e "## Warnings\n$WARNINGS" >> $GITHUB_STEP_SUMMARY
           fi
           if [[ ! -z "$LOAD_ERRORS" ]] || [[ ! -z "$ELISP_ERRORS" ]] || [[ "$EMACS_EXIT_CODE" != 0 ]]; then exit 1; fi
-
+      - name: Running MinEmacs in daemon mode
+        run: |
+          echo "Loading Emacs in daemon mode"
+          MINEMACSDIR=.github/workflows/scripts/minemacs-all.d/
+          make ci-daemon | tee /tmp/minemacs-output
+          EMACS_EXIT_CODE=$?
+          if [[ "$EMACS_EXIT_CODE" == 0 ]]; then
+            echo "Emacs exited successfully"
+          else
+            echo "Emacs exited with non-zero code ${EMACS_EXIT_CODE}"
+          fi
+          WARNINGS=$(cat /tmp/minemacs-output | grep Warning | sed -E 's/^(.*\.el): Warning/- \*\*\1\*\*/' | sed -E 's/^Warning ([^:]*)/- \*\*\1\*\*/')
+          LOAD_ERRORS=$(cat /tmp/minemacs-output | grep -E "(Cannot (open )?load)|(Not found)" | sed 's/^/- /')
+          ELISP_ERRORS=$(cat /tmp/minemacs-output | awk -F': ' '/^Debugger entered--Lisp error: / { print "- **" $1 "**: `" $2 "`"; print "```elisp"; while (getline && match($0, "^[[:space:]]{2}")) print $0; print "```"}' )
+          echo -e "# MinEmacs - always demand mode report ($EMACS_VERSION)\n" >> $GITHUB_STEP_SUMMARY
+          if [[ ! -z "$LOAD_ERRORS" ]]; then
+            echo -e "## Loading errors\n$LOAD_ERRORS\n" >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ ! -z "$ELISP_ERRORS" ]]; then
+            echo -e "## Emacs Lisp errors\n$ELISP_ERRORS\n" >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ ! -z "$WARNINGS" ]]; then
+            echo -e "## Warnings\n$WARNINGS" >> $GITHUB_STEP_SUMMARY
+          fi
